### ISSUE TITLE
Create better documentation

### ISSUE THREAD

**Issue by PinkCodez** [refact0r/studentvue#10]
Hello, I'm trying to sign into my studentvue with this service and it dosen't seem to be working. I keep getting a 401 error. Im not sure if im putting in the right link?

**Comment by refact0r** [comment]
It seems to me that the data formats for every district are slightly different, so I can only be sure that it will work for my school district. I'm sorry but this project has basically been put on hold since I don't have the time anymore. You're welcome to try and understand my spaghetti code, but if you want a working alternative I suggest looking elsewhere for now. Thanks.
